import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <html lang="en">
  <body className="flex flex-col min-h-screen">
    <main className="flex-grow">
      {children}
    </main>
    <footer className="w-full text-center text-sm text-gray-500 py-6">
      <p>Made with ❤️ by Alice Kim, daughter of Koen Woo Kim, L.Ac.</p>
      <p>Thank you for supporting a family business!</p>
    </footer>
  </body>
</html>

      </body>
    </html>
  );
}
